# Generated by Django 2.2.22 on 2021-05-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal',
            new_name='New',
        ),
    ]
